## ======================================================================
## resources
## ======================================================================

resource_types:
- name: http
  type: registry-image
  source:
    repository: 10.221.129.153:5000/registry/http-resource
    tag: v1.0
- name: merge-request
  type: registry-image
  source:
    repository: 10.221.129.153:5000/registry/gitlab-merge-request-resource
    tag: v1.0

resources:
- name: gpdb_pr
  type: merge-request
  source:
#    uri: "http://git.inspur.com/fanwenchang/hdb.git"
    uri: "http://10.110.27.118/fanwenchang/hdb.git"
    private_token: GotJADg5KkyfSzNesG35
    username: "majingwei"
    password: "321edc--"
    no_ssl: true
    project_id: 15136

- name: gpdb6-centos7-build
  type: registry-image 
  source:
    repository: 10.221.129.153:5000/registry/gpdb6-ubuntu18.04-build
    tag: v171

- name: gpdb6-centos7-test
  type: registry-image
  source:
    repository: 10.221.129.153:5000/registry/gpdb6-ubuntu18.04-test
    tag: v159

- name: python-centos7
  type: http
  source:
    index: http://10.221.129.153:8088
    regex: 'python-(?P<version>2\.7\.12).tar.gz'
    uri: 'http://10.221.129.153:8088/python-{version}.tar.gz'

jobs:
- name: compile_and_test_gpdb
  public: true
  max_in_flight: 10
  plan:
  - aggregate:
    - get: gpdb_pr
      trigger: true
      version: every
    - get: gpdb6-centos7-build
    - get: gpdb6-centos7-test
#    - get: libsigar-installer
#      resource: libsigar-centos7
    - get: python-tarball
      resource: python-centos7

#  - put: gpdb_pr
#    params:
#      path: gpdb_pr
#      status: pending
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: gpdb_pr
      params:
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
    do:
    - task: init gpdb_src  # Fetch tags and submodules, because the PR resource doesn't.
      image: gpdb6-centos7-build
      config:
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            echo '10.110.27.118 git.inspur.com' >> /etc/hosts &&
            git clone gpdb_pr gpdb_src &&
            cd gpdb_src &&
            #git fetch http://10.110.27.118/fanwenchang/hdb.git --tags &&
            git fetch http://oauth2:GotJADg5KkyfSzNesG35@git.inspur.com/fanwenchang/hdb.git --tags &&
            git branch 6X_STABLE_test2 &&
            git checkout 6X_STABLE_test2 &&
            git submodule update --init --recursive
        inputs: [{ name: gpdb_pr }]
        outputs: [{ name: gpdb_src }]
    - task: compile_gpdb_centos7
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      image: gpdb6-centos7-build
      params:
        CONFIGURE_FLAGS: ""
        TARGET_OS: ubuntu
        TARGET_OS_VERSION: 18.04 
        BLD_TARGETS: "clients loaders"
      timeout: 2h

